# Generated by Django 5.0.3 on 2024-03-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenationApp', '0002_visit_count_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffice_source', models.CharField(max_length=400, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('watch_time', models.IntegerField(default=0)),
                ('average_view_duration', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('impressions_clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
