# Generated by Django 5.0.3 on 2024-03-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamenationApp', '0003_trafficsource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficsource',
            old_name='traffice_source',
            new_name='traffic_source',
        ),
    ]
