# Generated by Django 5.0.3 on 2024-03-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamenationApp', '0004_rename_traffice_source_trafficsource_traffic_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficsource',
            name='average_view_duration',
        ),
    ]
