# Generated by Django 5.0.3 on 2024-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenationApp', '0005_remove_trafficsource_average_view_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsource',
            name='average_view_duration',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
